update test
Database-System/mid-exam pull request #20
Opened 2024-04-03 19:29 UTC by Huahua1222

2024-04-04 10:29 UTC, derrick921213 commented on src/Core/Controller.php
> +    }
你不知道ID是多少所以不能拿id

2024-04-04 10:37 UTC, derrick921213 commented on src/Core/Controller.php
> +    }
不需要使用FROM_UNIXTIME https://www.navicat.com/cht/company/aboutus/blog/1888-working-with-dates-and-times-in-mysql-part-1.html

2024-04-04 10:41 UTC, derrick921213 commented on tests/Controller_update_Test.php
> +    }
這裡會出問題

2024-04-04 10:41 UTC, derrick921213 requested changes
我寫好註解了

2024-04-05 08:34 UTC, Huahua1222 commented on src/Core/Controller.php
> +    }
course id是課程代碼，例如:1313、1314、2890這種，所以應該是知道課程代碼是多少的吧，所以我這邊沒有改

2024-04-06 07:43 UTC, derrick921213 requested changes
改updateCourse

2024-04-06 08:43 UTC, derrick921213 requested changes
fix

2024-04-06 09:26 UTC, derrick921213 approved these changes

2024-04-06 09:26 UTC, merged